services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_USERNAME: keycloakuser
      KC_DB_PASSWORD: password
      KC_HOSTNAME: localhost           
      KC_HTTP_PORT: 8080
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_PROXY: edge                  
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - keycloak-net
    command: start --optimized         

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloakuser
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    networks:
      - keycloak-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloakuser -d keycloak"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data:

networks:
  keycloak-net:
    driver: bridge